### ISSUE TITLE
Comments coming in on blogs feed

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#11]
Hi @ajmaradiaga , there are comments comming in on blogs feeds, e.g. https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/SAP-Fiori-blog-posts.xml

Was that a intended change? For me I would have prefered to just have original blog posts in feed.

**Comment by ajmaradiaga** [comment]
@abap-weasel Thanks for letting me know. Not intended at all.... I've not changed the code that generates the feed. Will check.

**Comment by abap-weasel** [comment]
@ajmaradiaga Any news on this issue by now? It looks like also topics get mixed up. 
e.g. this blog https://community.sap.com/t5/technology-blogs-by-sap/migration-of-sap-hana-on-premise-database-to-sap-hana-cloud/ba-p/13654501 is served from SAP Fiori feed (https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/SAP-Fiori-blog-posts.xml ) although it does not have the correspondig tag.

**Comment by ajmaradiaga** [comment]
I'm afraid that something changed in the API because comments are now coming in the response and you rightly point out... even content from other topics are coming through. Will see if I can find out something about what's going on.

**Comment by ajmaradiaga** [comment]
@abap-weasel the right data is now coming through in the system. You will see that reflected in the next refresh of the feeds.

**Comment by abap-weasel** [comment]
Hi @ajmaradiaga , I think there is another issue with the feeds now and they don't get updates at all. Can that be? 😥

**Comment by ajmaradiaga** [comment]
@abap-weasel apologies for the inconvenience.... someone included a secret/password within a blog post/q&a in SAP Community and GitHub scanning for secrets wasn't letting through the pushes because of that. The feeds are working fine now.
