### ISSUE TITLE
Please include [SAP Analytics Cloud] in the feed generator

### ISSUE THREAD

**Issue by xjhacking** [ajmaradiaga/feeds#13]
### Topic details

- Name: [SAP Analytics Cloud]
- URL: [https://pages.community.sap.com/topics/cloud-analytics]

You can find all topics here: https://pages.community.sap.com/topics

**Comment by ajmaradiaga** [comment]
I'll include it later today and let you know when it is ready :-)

**Comment by ajmaradiaga** [comment]
@xjhacking , the feeds for SAP Analytics Cloud are now available.
