### ISSUE TITLE
No Updates in Feeds anymore

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#15]
It looks like feeds aren't working anymore. 
Can you have a look @ajmaradiaga , please?

**Comment by ajmaradiaga** [comment]
Oh my... you are right, I don't see any commits in the last few days. Sorry about that. I will try accessing the service and see how I can get it running again remotely. 🤞

**Comment by ajmaradiaga** [comment]
@abap-weasel I fixed the issue. The feeds are working now. Apologies for the inconvenience. I need to set up an alerting mechanism so that this doesn't happen again.
