### ISSUE TITLE
Please include SAP Cloud Application Programming Model in the feed generator

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#2]
### Topic details

- Name: SAP Cloud Application Programming Model
- URL:  https://community.sap.com/t5/c-khhcw49343/SAP+Cloud+Application+Programming+Model/pd-p/9f13aee1-834c-4105-8e43-ee442775e5ce
- URL: https://pages.community.sap.com/topics/cloud-application-programming

**Comment by abap-weasel** [comment]
@ajmaradiaga please check

**Comment by ajmaradiaga** [comment]
@abap-weasel Apologies for not checking this before. I missed the notification somehow. I've included the topic.... it will be available in the next run.

**Comment by ajmaradiaga** [comment]
@abap-weasel it is now available - https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/SAP-Cloud-Application-Programming-Model-blog-posts.xml
