### ISSUE TITLE
Please include S/4HANA in the feed generator

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#3]
### Topic details

- Name: S/4HANA
- URL: https://community.sap.com/t5/c-khhcw49343/SAP+S%25252F4HANA/pd-p/73554900100800000266
- URL: https://community.sap.com/t5/tag/S4HANA/tg-p/board-id/consumer-productsblog-board

**Comment by abap-weasel** [comment]
@ajmaradiaga please check

**Comment by ajmaradiaga** [comment]
@abap-weasel It will be included in the next run.

**Comment by ajmaradiaga** [comment]
@abap-weasel it is now available - https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/SAP-S4HANA-blog-posts.xml
