### ISSUE TITLE
Please include Plant Maintenance in the feed generator

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#4]
### Topic details

- Name: Plant Maintenance
- URL: https://community.sap.com/t5/c-khhcw49343/PLM+Enterprise+Asset+Management+%252528EAM%252529%25252FPlant+Maintenance+%252528PM%252529/pd-p/430019464658497915145476514330950
- URL: https://community.sap.com/t5/c-khhcw49343/SAP+Predictive+Maintenance+and+Service%25252C+on-premise+edition/pd-p/73555000100800000307

**Comment by abap-weasel** [comment]
@ajmaradiaga please check

**Comment by ajmaradiaga** [comment]
@abap-weasel will be available in the next run

**Comment by ajmaradiaga** [comment]
@abap-weasel, I've added both:
- PLM EAM: https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/PLM-EAMPlant-Maintenance-blog-posts.xml
- SAP Predictive Maintenance and Service: https://github.com/ajmaradiaga/feeds/blob/main/scmt/topics/SAP-Predictive-Maintenance-and-Service-blog-posts.xml
