### ISSUE TITLE
Please include EWM in the feed generator

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#5]
### Topic details

- Name: EWM
- URL: https://community.sap.com/t5/c-khhcw49343/SAP+Extended+Warehouse+Management/pd-p/01200615320800000705

You can find all topics here: https://pages.community.sap.com/topics

**Comment by abap-weasel** [comment]
@ajmaradiaga please check

**Comment by ajmaradiaga** [comment]
@abap-weasel will be in the next run

**Comment by ajmaradiaga** [comment]
@abap-weasel I've added it: https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/SAP-Integration-Strategy-blog-posts.xml
