### ISSUE TITLE
Please include horst_keller in the feed generator

### ISSUE THREAD

**Issue by abap-weasel** [ajmaradiaga/feeds#7]
### Community member details

- Name: horst_keller
- Username: horst_keller
- Profile URL: https://community.sap.com/t5/user/viewprofilepage/user-id/181866

**Comment by abap-weasel** [comment]
@ajmaradiaga please check

**Comment by ajmaradiaga** [comment]
@abap-weasel I've included the horst_keller - https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/members/sap-community-members/horst_keller.xml
