### ISSUE TITLE
Feed URL not getting updated on relevant post

### ISSUE THREAD

**Issue by boskamp** [ajmaradiaga/feeds#8]
Hello, I've subscribed to your feed 
```
https://raw.githubusercontent.com/ajmaradiaga/feeds/main/scmt/topics/SAP-Cloud-Identity-Access-Governance-qa.xml
```
and believe it should contain the following new post:

```
https://community.sap.com/t5/technology-q-a/in-iag-pam-is-there-possibility-to-enable-mandatory-approval-of-2-or-more/qaq-p/13627592
```
However, it doesn't. Please check whether the regular update is still working.

**Comment by ajmaradiaga** [comment]
@boskamp, I will check

**Comment by ajmaradiaga** [comment]
@boskamp The entry is in the feed. This particular feed updates twice a day, it is not immediate.... therefore it will take some time to appear. You can see that it was included in this [commit](https://github.com/ajmaradiaga/feeds/commit/00eb164864981e6e7c9a3e85d3ae861b52765ae8#diff-1d7b43dd8c9789ee974ffa1d8fdefa05a1f7599cd4e4c211aea70739e9a5fdb0)

**Screenshot of entry in feed:**
<img width="1140" alt="image" src="https://github.com/ajmaradiaga/feeds/assets/736429/36a25c31-f78e-4354-9b95-fea0e2873e8a">
